//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBRepacker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string OpenExtractPath {
            get {
                return ((string)(this["OpenExtractPath"]));
            }
            set {
                this["OpenExtractPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string OutputExtractPAC {
            get {
                return ((string)(this["OutputExtractPAC"]));
            }
            set {
                this["OutputExtractPAC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string OutputRepackPAC {
            get {
                return ((string)(this["OutputRepackPAC"]));
            }
            set {
                this["OutputRepackPAC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool outputWAV {
            get {
                return ((bool)(this["outputWAV"]));
            }
            set {
                this["outputWAV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string OpenRepackPath {
            get {
                return ((string)(this["OpenRepackPath"]));
            }
            set {
                this["OpenRepackPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string VBNPathNUDtoDAE {
            get {
                return ((string)(this["VBNPathNUDtoDAE"]));
            }
            set {
                this["VBNPathNUDtoDAE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string NUDPathNUDtoDAE {
            get {
                return ((string)(this["NUDPathNUDtoDAE"]));
            }
            set {
                this["NUDPathNUDtoDAE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string OutputPathNUDtoDAE {
            get {
                return ((string)(this["OutputPathNUDtoDAE"]));
            }
            set {
                this["OutputPathNUDtoDAE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string DAEPathDAEtoNUD {
            get {
                return ((string)(this["DAEPathDAEtoNUD"]));
            }
            set {
                this["DAEPathDAEtoNUD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string OutputPathDAEtoNUD {
            get {
                return ((string)(this["OutputPathDAEtoNUD"]));
            }
            set {
                this["OutputPathDAEtoNUD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string VBNPathDAEtoNUD {
            get {
                return ((string)(this["VBNPathDAEtoNUD"]));
            }
            set {
                this["VBNPathDAEtoNUD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportVBN {
            get {
                return ((bool)(this["exportVBN"]));
            }
            set {
                this["exportVBN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string OutputRepackPsarc {
            get {
                return ((string)(this["OutputRepackPsarc"]));
            }
            set {
                this["OutputRepackPsarc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string PsarcRepackFolder {
            get {
                return ((string)(this["PsarcRepackFolder"]));
            }
            set {
                this["PsarcRepackFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string PsarcPACFilePathList {
            get {
                return ((string)(this["PsarcPACFilePathList"]));
            }
            set {
                this["PsarcPACFilePathList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("patch")]
        public string PsarcOutputFileName {
            get {
                return ((string)(this["PsarcOutputFileName"]));
            }
            set {
                this["PsarcOutputFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedTab {
            get {
                return ((int)(this["SelectedTab"]));
            }
            set {
                this["SelectedTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string MBONDataFolderPath {
            get {
                return ((string)(this["MBONDataFolderPath"]));
            }
            set {
                this["MBONDataFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string FBDataFolderPath {
            get {
                return ((string)(this["FBDataFolderPath"]));
            }
            set {
                this["FBDataFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputDataFolderPath {
            get {
                return ((string)(this["outputDataFolderPath"]));
            }
            set {
                this["outputDataFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string CScriptFilePath {
            get {
                return ((string)(this["CScriptFilePath"]));
            }
            set {
                this["CScriptFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string BABBFilePath {
            get {
                return ((string)(this["BABBFilePath"]));
            }
            set {
                this["BABBFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputScriptFolderPath {
            get {
                return ((string)(this["outputScriptFolderPath"]));
            }
            set {
                this["outputScriptFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool scriptBigEndian {
            get {
                return ((bool)(this["scriptBigEndian"]));
            }
            set {
                this["scriptBigEndian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public int MinScriptPointer {
            get {
                return ((int)(this["MinScriptPointer"]));
            }
            set {
                this["MinScriptPointer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string B4ACFilePath {
            get {
                return ((string)(this["B4ACFilePath"]));
            }
            set {
                this["B4ACFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string ProjecitleBinaryFilePath {
            get {
                return ((string)(this["ProjecitleBinaryFilePath"]));
            }
            set {
                this["ProjecitleBinaryFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputProjectileJSONFolderPath {
            get {
                return ((string)(this["outputProjectileJSONFolderPath"]));
            }
            set {
                this["outputProjectileJSONFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string ProjecitleJSONFilePath {
            get {
                return ((string)(this["ProjecitleJSONFilePath"]));
            }
            set {
                this["ProjecitleJSONFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputProjectileBinFolderPath {
            get {
                return ((string)(this["outputProjectileBinFolderPath"]));
            }
            set {
                this["outputProjectileBinFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ProjectileBinaryInputGameVer {
            get {
                return ((int)(this["ProjectileBinaryInputGameVer"]));
            }
            set {
                this["ProjectileBinaryInputGameVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool convertMBONProjecitle {
            get {
                return ((bool)(this["convertMBONProjecitle"]));
            }
            set {
                this["convertMBONProjecitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string ReloadBinaryFilePath {
            get {
                return ((string)(this["ReloadBinaryFilePath"]));
            }
            set {
                this["ReloadBinaryFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputReloadJSONFolderPath {
            get {
                return ((string)(this["outputReloadJSONFolderPath"]));
            }
            set {
                this["outputReloadJSONFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string ReloadJSONFilePath {
            get {
                return ((string)(this["ReloadJSONFilePath"]));
            }
            set {
                this["ReloadJSONFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputReloadBinFolderPath {
            get {
                return ((string)(this["outputReloadBinFolderPath"]));
            }
            set {
                this["outputReloadBinFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ReloadBinaryInputGameVer {
            get {
                return ((int)(this["ReloadBinaryInputGameVer"]));
            }
            set {
                this["ReloadBinaryInputGameVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool convertMBONReload {
            get {
                return ((bool)(this["convertMBONReload"]));
            }
            set {
                this["convertMBONReload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string HitBinaryFilePath {
            get {
                return ((string)(this["HitBinaryFilePath"]));
            }
            set {
                this["HitBinaryFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputHitJSONFolderPath {
            get {
                return ((string)(this["outputHitJSONFolderPath"]));
            }
            set {
                this["outputHitJSONFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string HitJSONFilePath {
            get {
                return ((string)(this["HitJSONFilePath"]));
            }
            set {
                this["HitJSONFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputHitBinFolderPath {
            get {
                return ((string)(this["outputHitBinFolderPath"]));
            }
            set {
                this["outputHitBinFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int HitBinaryInputGameVer {
            get {
                return ((int)(this["HitBinaryInputGameVer"]));
            }
            set {
                this["HitBinaryInputGameVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool convertMBONHit {
            get {
                return ((bool)(this["convertMBONHit"]));
            }
            set {
                this["convertMBONHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string ALEOFolderPath {
            get {
                return ((string)(this["ALEOFolderPath"]));
            }
            set {
                this["ALEOFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputALEOFolderPath {
            get {
                return ((string)(this["outputALEOFolderPath"]));
            }
            set {
                this["outputALEOFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputVoiceLogicBinary {
            get {
                return ((string)(this["inputVoiceLogicBinary"]));
            }
            set {
                this["inputVoiceLogicBinary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputVoiceLogicJSONFolder {
            get {
                return ((string)(this["outputVoiceLogicJSONFolder"]));
            }
            set {
                this["outputVoiceLogicJSONFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputVoiceLogicJSON {
            get {
                return ((string)(this["inputVoiceLogicJSON"]));
            }
            set {
                this["inputVoiceLogicJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputVoiceLogicBinaryFolder {
            get {
                return ((string)(this["outputVoiceLogicBinaryFolder"]));
            }
            set {
                this["outputVoiceLogicBinaryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputNus3File {
            get {
                return ((string)(this["inputNus3File"]));
            }
            set {
                this["inputNus3File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputNameandHashFolder {
            get {
                return ((string)(this["outputNameandHashFolder"]));
            }
            set {
                this["outputNameandHashFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Nus3SoundHashFormat {
            get {
                return ((int)(this["Nus3SoundHashFormat"]));
            }
            set {
                this["Nus3SoundHashFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string soundHashMainTitle {
            get {
                return ((string)(this["soundHashMainTitle"]));
            }
            set {
                this["soundHashMainTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputLMBFilePath {
            get {
                return ((string)(this["inputLMBFilePath"]));
            }
            set {
                this["inputLMBFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputLMBFolderPath {
            get {
                return ((string)(this["outputLMBFolderPath"]));
            }
            set {
                this["outputLMBFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputFBUnitInfoListBinary {
            get {
                return ((string)(this["inputFBUnitInfoListBinary"]));
            }
            set {
                this["inputFBUnitInfoListBinary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputFBUnitInfoListJSONFolder {
            get {
                return ((string)(this["outputFBUnitInfoListJSONFolder"]));
            }
            set {
                this["outputFBUnitInfoListJSONFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputFBUnitInfoListJSON {
            get {
                return ((string)(this["inputFBUnitInfoListJSON"]));
            }
            set {
                this["inputFBUnitInfoListJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputFBUnitInfoListBinaryFolder {
            get {
                return ((string)(this["outputFBUnitInfoListBinaryFolder"]));
            }
            set {
                this["outputFBUnitInfoListBinaryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputMeleeVarBinaryPath {
            get {
                return ((string)(this["inputMeleeVarBinaryPath"]));
            }
            set {
                this["inputMeleeVarBinaryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputFBSeriesInfoListBinary {
            get {
                return ((string)(this["inputFBSeriesInfoListBinary"]));
            }
            set {
                this["inputFBSeriesInfoListBinary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputFBSeriesInfoListJSONFolder {
            get {
                return ((string)(this["outputFBSeriesInfoListJSONFolder"]));
            }
            set {
                this["outputFBSeriesInfoListJSONFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputFBSeriesInfoListJSON {
            get {
                return ((string)(this["inputFBSeriesInfoListJSON"]));
            }
            set {
                this["inputFBSeriesInfoListJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputFBSeriesInfoListBinaryFolder {
            get {
                return ((string)(this["outputFBSeriesInfoListBinaryFolder"]));
            }
            set {
                this["outputFBSeriesInfoListBinaryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputNTXBBinaryPath {
            get {
                return ((string)(this["inputNTXBBinaryPath"]));
            }
            set {
                this["inputNTXBBinaryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputNTXBJSONPath {
            get {
                return ((string)(this["outputNTXBJSONPath"]));
            }
            set {
                this["outputNTXBJSONPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputNTXBJSONPath {
            get {
                return ((string)(this["inputNTXBJSONPath"]));
            }
            set {
                this["inputNTXBJSONPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputNTXBBinaryPath {
            get {
                return ((string)(this["outputNTXBBinaryPath"]));
            }
            set {
                this["outputNTXBBinaryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputUnitDataHashSchemaBinary {
            get {
                return ((string)(this["inputUnitDataHashSchemaBinary"]));
            }
            set {
                this["inputUnitDataHashSchemaBinary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputUnitDataHashSchemaJSONPath {
            get {
                return ((string)(this["outputUnitDataHashSchemaJSONPath"]));
            }
            set {
                this["outputUnitDataHashSchemaJSONPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputUnitDataHashSchemaJSON {
            get {
                return ((string)(this["inputUnitDataHashSchemaJSON"]));
            }
            set {
                this["inputUnitDataHashSchemaJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputUnitDataBinary {
            get {
                return ((string)(this["inputUnitDataBinary"]));
            }
            set {
                this["inputUnitDataBinary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputUnitDataJSONPath {
            get {
                return ((string)(this["outputUnitDataJSONPath"]));
            }
            set {
                this["outputUnitDataJSONPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string inputUnitDataJSON {
            get {
                return ((string)(this["inputUnitDataJSON"]));
            }
            set {
                this["inputUnitDataJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string outputUnitDataBinaryPath {
            get {
                return ((string)(this["outputUnitDataBinaryPath"]));
            }
            set {
                this["outputUnitDataBinaryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool convertMBONUnitData {
            get {
                return ((bool)(this["convertMBONUnitData"]));
            }
            set {
                this["convertMBONUnitData"] = value;
            }
        }
    }
}
